name: CI Pipeline for Jest Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest  # Alternatively, 'windows-latest' or 'macos-latest' if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies on BE
      run: npm ci  # Using npm ci for faster, consistent installs
      working-directory: ./ModuleRegistry/BE

    - name: Install dependencies on FE
      run: npm ci  # Using npm ci for faster, consistent installs
      working-directory: ./ModuleRegistry/FE
    
    - name: Run Jest tests
      run: npm test
      working-directory: ./ModuleRegistry/BE
