name: CI Workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version here

    - name: Install dependencies
      run: npm install --no-audit --prefer-offline
      working-directory: ./BE  # Adjust path if necessary

    - name: Npm check updates
      uses: Fzwael/ncu-action@v1.4.0
      with:
        ncu-options: --upgrade --semverLevel minor  # Adjust options as needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for ncu-action to create PRs

    - name: Run Jest tests
      run: npm test
      working-directory: ./BE  # Adjust path if necessary
