name: CI Workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version here

    - name: Install dependencies -- BE
      run: npm install --no-audit --prefer-offline
      working-directory: ./BE 

    - name: Install dependencies FE
      run: npm install --no-audit --prefer-offline
      working-directory: ./FE
