name: Auto Merge Dev to Deployment

on:
  schedule:
    - cron: "0 9 * * 3" # Every Wednesday at 4:00 am ET
    - cron: "0 9 * * 6" # Every Saturday at 4:00 am ET
  workflow_dispatch: # Allow manual triggering as well

jobs:
  merge:
    environment: staging
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      # Checkout the dev branch
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev # This checks out the dev branch

      # Create Pull Request from dev to deployment
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: deployment # Set the target branch for the PR
          title: "Automated Merge from Dev to Deployment"
          body: "Scheduled merge from dev branch."
          commit-message: "Merge dev branch into deployment"
          delete-branch: false # Keep the dev branch

      # Find and approve the pull request
      - name: Find and Approve Pull Request
        id: approve-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const pr = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'dev',
              base: 'deployment'
            });
            
            if (pr.data.length > 0) {
              const pullRequest = pr.data[0];
              await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                event: 'APPROVE'
              });
              return pullRequest.number;
            } else {
              throw new Error("No open PR found from dev to deployment");
            }

      # Merge the approved pull request
      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const pull_number = core.getInput('approve-pr', { required: true });
            if (pull_number) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull_number
              });
            }
